USE JUEGOS
/*CREATE PROCEDURE ELIMINA_JUEGO
@wcodigo INT
AS BEGIN
IF EXISTS (SELECT * FROM JUEGOS WHERE codigo=@wcodigo)
BEGIN
	DELETE JUEGOS WHERE codigo=@wcodigo
	RETURN
END
ELSE PRINT 'ESTE JUEGO NO EXISTE'
END

DROP ELIMINA_JUEGO

CREATE PROCEDURE ACTUALIZAR_JUEGO
@wcodigo INT, @wnombre VARCHAR(30), @wcategoria VARCHAR(30), @wprecio MONEY
AS BEGIN
IF EXISTS (SELECT * FROM JUEGOS WHERE codigo=@wcodigo)
BEGIN
	UPDATE JUEGOS SET nombre=@wnombre WHERE codigo=@wcodigo
	UPDATE JUEGOS SET categoria=@wcategoria WHERE codigo=@wcodigo
	UPDATE JUEGOS SET precio=@wprecio WHERE codigo=@wcodigo
	RETURN
END
ELSE PRINT 'ESTE JUEGO NO EXISTE'
END*/